name: Build Azkaban

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360
    steps:
      - name: Checkout Azkaban
        uses: actions/checkout@v3
      - name: Export version to variable
        run: |
            export AZKABAN_VERSION=$(cat version)
            echo "AZKABAN_VERSION=$AZKABAN_VERSION" >> $GITHUB_ENV
        shell: bash
      - name: Checkout Upstream Azkaban
        uses: actions/checkout@v3
        with:
          repository: azkaban/azkaban
          path: azkaban
          ref: ${{ env.AZKABAN_VERSION }}
          fetch-depth: 1
      - name: Build Azkaban
        run: |
          mkdir releasefiles jdk
          wget -q --no-check-certificate --no-cookies \
              --header "Cookie: oraclelicense=accept-securebackup-cookie"  \
              https://download.oracle.com/otn/java/jdk/8u391-b13/b291ca3e0c8548b5a51d5a5f50063037/jdk-8u391-linux-x64.tar.gz -O jdk.tar.gz
          tar -xf jdk.tar.gz
          export JAVA_HOME="$PWD/jdk1.8.0_391"
          sed -i 's#https://nodejs.org/dist#https://mirrors.dotsrc.org/nodejs/release#g'  azkaban-web-server/build.gradle
          ./gradlew build -x test -Pversion=3.8.22
          if [[ $? -ne 0 ]]
          then
            for x in $(find -maxdepth 4 -type f -name 'azkaban-*0.1.0-SNAPSHOT.zip' -o -name 'azkaban-*0.1.0-SNAPSHOT.tar.gz')
            do
              cp $x releasefiles/
            done
          fi
        shell: bash
        working-directory: azkaban

      - name: Calculate SHA256 checksum
        run: |
          for filename in azkaban-*; do shasum -a 256 ${filename} | tee ${filename}.sha256 ; done
        shell: bash
        working-directory: azkaban/releasefiles

      - uses: actions/upload-artifact@v3
        if: github.ref != 'refs/heads/main'
        with:
          name: azkaban distributions
          retention-days: 5
          path: |
            azkaban/releasefiles/azkaban-*.tar.gz
            azkaban/releasefiles/azkaban-*.zip
            azkaban/releasefiles/azkaban-*.sha256

      - name: Generate Changelog
        run: curl -s https://api.github.com/repos/azkaban/azkaban/releases/latest | jq -r 'select(.prerelease == false) | .body[0:]' > ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: v${{ env.AZKABAN_VERSION }}
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: | 
            azkaban/releasefiles/azkaban-*.tar.gz
            azkaban/releasefiles/azkaban-*.zip
            azkaban/releasefiles/azkaban-*.sha256
      - name: Latest
        uses: softprops/action-gh-release@v0.1.15
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: Latest
          files: | 
            azkaban/releasefiles/azkaban-*.tar.gz
            azkaban/releasefiles/azkaban-*.zip
            azkaban/releasefiles/azkaban-*.sha256
